CREATE TABLE GOOGLE_ADS (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    account_id INT,
    account_name NVARCHAR(50),  
    ad_group_id BIGINT,
    ad_id BIGINT,
    ad_group_name NVARCHAR(120), 
    campaign_resource_name NVARCHAR(255), 
    campaign_id BIGINT,
    campaign_name NVARCHAR(255), 
    campaign_start_date DATE,
    campaign_end_date DATE,
    clicks BIGINT,
    conversions DOUBLE,
    cost BIGINT,
    impressions BIGINT,
    ctr DOUBLE,
    cost_per_conversion DOUBLE,
    average_cost DOUBLE,
    average_cpc DOUBLE,
    conversions_from_interactions_rate DOUBLE,
    created_at date NOT NULL,
    updated_at date NOT NULL,
    created_by NVARCHAR(255),  
    updated_by NVARCHAR(255)  
);
